import Link from 'next/link';
const createExample = JSON.stringify({ shipmentId: 'wasla-shipment-id', trackingCode: 'WASLA-tracking-code', orderNumber: 'ORDER-1001', pickup: { name: 'فرع المتجر', phone: 'TEST_PHONE', address: 'عنوان الاستلام', lat: 15.5, lng: 32.56 }, dropoff: { name: 'العميل', phone: 'TEST_PHONE', address: 'عنوان التسليم', lat: 15.51, lng: 32.56 }, codAmount: 1000, currency: 'SDG' }, null, 2);
const signatureExample = `import { createHmac } from 'node:crypto';
const raw = JSON.stringify({
  providerReference: 'REFERENCE_FROM_CREATE',
  status: 'IN_TRANSIT'
});
const signature = createHmac('sha256', process.env.WASLA_WEBHOOK_SECRET)
  .update(raw).digest('hex');
await fetch(process.env.WASLA_WEBHOOK_URL, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json', 'x-wasla-signature': signature },
  body: raw
});`;
export function IntegrationGuide({ origin }: { origin: string }) {
  return <div className="mx-auto max-w-5xl space-y-7" dir="rtl">
    <header className="rounded-2xl border bg-[var(--card)] p-7"><p className="text-sm font-bold text-[var(--primary)]">WASLA Developers · Shipping v1</p><h1 className="mt-3 text-3xl font-black">دليل ربط شركات التوصيل</h1><p className="mt-4 leading-8 text-[var(--muted-foreground)]">من تفعيل الشركة في المتجر، إلى إعداد التطبيق واختبار البوليصة وتحديث حالة الطلب. هذا الدليل يصف العقد البرمجي الحالي لوصلة، وليس واجهات سلة.</p></header>
    <nav aria-label="فهرس دليل الربط" className="flex flex-wrap gap-3 text-sm">{[['merchant','للتاجر'],['setup','تجهيز الشريك'],['production','إنشاء الشحنة'],['webhooks','عكس الحالات'],['sandbox','API الاختبار'],['errors','الأخطاء والإطلاق']].map(([id,label]) => <a key={id} href={`#${id}`} className="rounded-full border bg-[var(--card)] px-4 py-2">{label}</a>)}</nav>
    <Section id="merchant" title="01 — التاجر: كيف أفعل التوصيل؟"><ol className="list-decimal space-y-3 ps-6"><li>من لوحة التاجر ← التوصيل ← شركاء التوصيل، اختر شركة منشورة ومعتمدة ثم فعّلها.</li><li>أكمل موقع الفرع وإحداثيات عنوان العميل. تسمية المدينة وحدها لا تكفي لحساب التغطية.</li><li>تظهر العروض وفق مناطق الشركة وأسعارها والمسافة وحالة الطلب. عدم ظهور عرض قد يعني أن العنوان خارج التغطية.</li><li>قبول العرض ينشئ الشحنة. تظهر تحديثات الشريك على الطلب، ومنها خرج للتوصيل وتم التسليم.</li><li>لا ترسل كلمة مرور متجرك أو مفتاح حسابك لشركة الشحن. لا يحتاج التاجر كتابة كود لتفعيل شركة منشورة.</li></ol><p>تفعيل الشركة لا يلغي ضرورة الاتفاق على التحصيل والتسويات والإلغاء والدعم معها.</p></Section>
    <Section id="setup" title="02 — الشريك: من التسجيل إلى النشر"><ol className="list-decimal space-y-3 ps-6"><li>أنشئ حساب شركة وأكّد البريد أو واتساب من أمان الحساب.</li><li>ارفع الشعار مباشرة، وأكمل الوصف وبريد الدعم وروابط السياسات.</li><li>أضف مناطق الخدمة وحدودها الفعلية والأسعار. دليل السودان اقتراح أسماء وليس تغطية تلقائية.</li><li>اختبر الدورة في متجر Sandbox الخاص بك، ثم جهّز عنوان HTTPS لنظام شركتك ومفتاحه.</li><li>اطلب اعتماد نطاق API من إدارة وصلة؛ لا يمكن استخدام عنوان داخلي أو غير معتمد.</li><li>أرسل التطبيق للمراجعة. إعداد البيانات لا ينشر التطبيق تلقائياً للتجار.</li></ol><p className="rounded-xl bg-[var(--muted)] p-4">المصادقة الحالية: مفتاح Bearer بين الخوادم، وتوقيع HMAC للشركة عند إرسال الحالات. OAuth وسوق تطبيقات عامة الصلاحيات غير متاحين في هذا الإصدار.</p></Section>
    <Section id="production" title="03 — الإنتاج: وصلة تطلب إنشاء شحنة من نظام الشركة"><Endpoint method="POST" path="{YOUR_API_BASE_URL}/shipments" /><p>هذا المسار تنفذه شركة التوصيل في نظامها، وليس مسار إنشاء عام داخل وصلة. تستدعيه وصلة من الخادم بعد قبول عرض التوصيل.</p><Code value={`Authorization: Bearer YOUR_PROVIDER_SECRET\nContent-Type: application/json\nIdempotency-Key: WASLA_SHIPMENT_ID`} /><Code value={createExample} /><p>أعد استجابة JSON ناجحة تتضمن مرجعاً فريداً داخل شركتك:</p><Code value={'{"providerReference":"CARRIER-12345"}'} /><ul className="list-disc space-y-2 ps-6"><li>يجب أن يكون المرجع نصاً بطول 1–200 حرف. احتفظ بربطه بمعرّف الشحنة من وصلة.</li><li>أعد المرجع نفسه عند تكرار مفتاح Idempotency-Key، ولا تنشئ شحنتين.</li><li>مهلة الاتصال 10 ثوانٍ؛ لا توجد إعادة توجيه HTTP. المعالجة القابلة للإعادة تستخدم عامل المهام عند تهيئته.</li><li>codAmount قيمة التحصيل في المسار الحالي، وcurrency عملة الشحنة. يجب اختبار اتفاق التحصيل قبل تفعيل الشركة.</li></ul><p className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950">تنزيل بوليصة شركة حقيقية أو طلب إلغاء تلقائي إلى API الشركة غير متاحين في عقد الإنتاج الحالي. البوليصة والإلغاء في قسم Sandbox محاكاة للاختبار فقط؛ يلزم استكمال عقد الشركة واختباره قبل الاعتماد على هاتين العمليتين إنتاجياً.</p></Section>
    <Section id="webhooks" title="04 — توقيع الإشعارات وعكس حالة الطلب"><Endpoint method="POST" path={`${origin}/api/webhooks/delivery-partners/{WEBHOOK_TOKEN}`} /><p>انسخ عنوان الاستقبال الخاص بشركتك من التطبيق والتكامل. وقّع النص الخام للطلب بمفتاح الشركة المحفوظ في إعدادات الربط، وأرسل التوقيع في x-wasla-signature. لا تعِد تنسيق JSON بعد توقيعه.</p><Code value={signatureExample} /><div className="overflow-auto"><table className="w-full text-start text-sm"><thead><tr><th className="p-3 text-start">حالة الشحنة</th><th className="p-3 text-start">أثرها على الطلب</th></tr></thead><tbody>{[['ASSIGNED','تعيين المندوب؛ لا يغير الطلب'],['PICKED_UP / IN_TRANSIT','يحوّل الطلب الجاهز إلى OUT_FOR_DELIVERY'],['DELIVERED','يحوّل الطلب إلى DELIVERED'],['FAILED','فشل التوصيل؛ يحتاج متابعة تشغيلية'],['CANCELLED','إلغاء الشحنة قبل الاستلام؛ لا يلغي الطلب التجاري تلقائياً']].map(([state,effect]) => <tr key={state} className="border-t"><td dir="ltr" className="p-3 font-mono">{state}</td><td className="p-3">{effect}</td></tr>)}</tbody></table></div><p>الحد الأقصى 32KB. الحقول: providerReference، status، وnote اختياري حتى 1000 حرف في الإنتاج. استجابة النجاح 200 مع success:true. التكرار والحالات المتأخرة لا تُنشئ تغييرات مكررة. توقيع خاطئ أو مرجع غير معروف أو انتقال غير مسموح يعيد 400. لا تعاود إرسال طلب خاطئ دون تصحيحه.</p></Section>
    <Section id="sandbox" title="05 — متجر الاختبار وAPI المعزول"><p>من متجر الاختبار أنشئ مساحة شركتك. تحصل على مفتاح يبدأ بـ wsl_test_ ورابط Webhook مستقل. هذه المفاتيح لا تعمل على بيانات التجار الحقيقيين. لا تُدخل بيانات عملاء حقيقيين.</p><Endpoint method="POST" path={`${origin}/api/partner-sandbox/shipments`} /><Code value={`curl -X POST '${origin}/api/partner-sandbox/shipments' \\\n  -H 'Authorization: Bearer YOUR_SANDBOX_KEY' \\\n  -H 'Idempotency-Key: sandbox-order-001'`} /><p>ينشئ طلباً ثابتاً وبوليصة تجريبية. لا يحتاج جسم الطلب ولا يرسل شيئاً لشركة الشحن. الاستجابة 201: sandbox، providerReference، trackingCode، status، orderStatus، labelPath. عرض البوليصة يتطلب تسجيل الدخول لنفس الشركة.</p><Endpoint method="POST" path={`${origin}/api/partner-sandbox/shipments/{ID}/cancel`} /><p>نفس Bearer الخاص بمتجر الاختبار. الإلغاء متاح قبل الاستلام فقط؛ تكرار إلغاء نفس الشحنة آمن. تصبح البوليصة موسومة «ملغاة».</p><Endpoint method="POST" path={`${origin}/api/partner-sandbox/webhooks/{TOKEN}`} /><p>استخدم مثال HMAC أعلاه مع مفتاح ورابط Sandbox. الحقول المطلوبة حصراً: providerReference وstatus. يتم تحديث الطلب التجريبي وسجل الحالات داخل البوابة. مفتاح متجر آخر أو توقيع خاطئ لا يستطيع تحديث شحنتك.</p><ul className="list-disc space-y-2 ps-6"><li>الحد: متجر واحد و100 شحنة لكل شركة في هذه النسخة.</li><li>دوّر المفتاح من صاحب حساب الشريك عند الحاجة؛ المفتاح القديم يتوقف فوراً.</li><li>اختبر الإنشاء المكرر، الإلغاء قبل وبعد الاستلام، التسليم، التوقيع الخاطئ، والحالة المكررة.</li></ul></Section>
    <Section id="errors" title="06 — استكشاف الأخطاء وبوابة الإطلاق"><ul className="list-disc space-y-3 ps-6"><li>401 في Sandbox: المفتاح غير صحيح أو مدوّر أو الحساب موقوف.</li><li>400: بيانات غير صحيحة أو توقيع/حالة غير صالحة أو بلوغ حد الشحنات.</li><li>409 عند الإلغاء: الشحنة غير تابعة للمتجر أو تجاوزت مرحلة السماح بالإلغاء.</li><li>429: حد الطلبات؛ انتظر قبل المحاولة مجدداً.</li><li>404 لصفحة التغطية: تحقق من نشر آخر main الصحيح، ومسار الصفحة داخل صورة البناء؛ ليست مشكلة بيانات المناطق.</li><li>الصور بعد إعادة النشر: تحقق من ربط التخزين الدائم أو إعداد S3.</li></ul><p>لا تعتبر الشركة جاهزة للإطلاق قبل اختبار حساب معتمد، نطاق HTTPS، حفظ آمن للأسرار، عامل إعادة المحاولة، تغطية وتسعيرة صحيحتين، وعكس حالات من نظامها الحقيقي. نجاح المحاكاة وحده لا يثبت هذا الربط.</p><Link className="inline-block underline" href="/partners">التواصل والانضمام لشركاء وصلة</Link></Section>
  </div>;
}
function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-6 space-y-5 rounded-2xl border bg-[var(--card)] p-6 leading-7"><h2 className="text-xl font-black">{title}</h2>{children}</section>; }
function Endpoint({ method, path }: { method: string; path: string }) { return <div dir="ltr" className="flex flex-wrap gap-3 rounded-xl bg-slate-950 p-4 text-sm text-white"><strong className="text-emerald-300">{method}</strong><code className="break-all">{path}</code></div>; }
function Code({ value }: { value: string }) { return <pre dir="ltr" className="overflow-auto rounded-xl bg-slate-950 p-5 text-left text-xs leading-6 text-slate-100"><code>{value}</code></pre>; }
