import { PLATFORM_PERMISSIONS, requirePlatformPermission } from '@/lib/platform-permissions';
import { reviewAcquisitionApplicationAction } from '@/modules/marketer-applications/actions';
import { reviewMarketerIdentityAction } from '@/modules/marketer-portal/actions';
import { listAcquisitionApplicationsForAdmin } from '@/modules/marketer-applications/marketer-applications.service';
import prisma from '@/lib/db/prisma';

export const dynamic = 'force-dynamic';

const statusName = { PENDING: 'قيد المراجعة', APPROVED: 'مقبول', REJECTED: 'مرفوض' } as const;

export default async function AdminMarketersPage() {
  await requirePlatformPermission(PLATFORM_PERMISSIONS.MERCHANTS_MANAGE);
  const [applications, referrals, commissions, verifications] = await Promise.all([
    listAcquisitionApplicationsForAdmin(),
    prisma.marketerMerchantReferral.findMany({ include: { marketerAccount: { include: { user: { select: { name: true, email: true } } } }, referredMerchant: { select: { name: true } } }, orderBy: { registeredAt: 'desc' }, take: 200 }),
    prisma.marketerSubscriptionCommission.findMany({ include: { marketerAccount: { include: { user: { select: { name: true } } } }, referralRecord: { include: { referredMerchant: { select: { name: true } } } } }, orderBy: { createdAt: 'desc' }, take: 200 }),
    prisma.marketerIdentityVerification.findMany({ include: { marketerAccount: { include: { user: { select: { name: true, email: true } } } }, documents: { select: { id: true, fileName: true } } }, orderBy: [{ status: 'asc' }, { submittedAt: 'desc' }], take: 100 }),
  ]);
  return <div className="space-y-7" dir="rtl"><header><p className="font-bold text-[var(--primary)]">شركاء النمو</p><h1 className="mt-2 text-2xl font-black">طلبات مسوقي استقطاب التجار</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-[var(--muted-foreground)]">مراجعة أولية قبل التعاقد وKYC وإصدار رابط الإحالة. القبول هنا لا ينشئ التزاماً مالياً تلقائياً.</p></header>
    <section className="grid gap-4">{applications.map(item=><article key={item.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black">{item.name}</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]" dir="ltr">{item.phone} · {item.email}</p><p className="mt-1 text-sm">{item.city} · {item.channels.join('، ')}</p></div><span className="rounded-full bg-[var(--muted)] px-3 py-1 text-xs font-bold">{statusName[item.status]}</span></div>{item.experience&&<p className="mt-4 rounded-xl bg-[var(--muted)] p-3 text-sm leading-6">{item.experience}</p>}<div className="mt-3 flex flex-wrap gap-4 text-xs text-[var(--muted-foreground)]"><span>الجمهور: {item.audienceSize?.toLocaleString('ar-SD')??'غير محدد'}</span>{item.portfolioUrl&&<a href={item.portfolioUrl} target="_blank" rel="noreferrer" className="text-[var(--primary)] underline">رابط الأعمال</a>}<span>{item.createdAt.toLocaleString('ar-SD')}</span></div>{item.notes&&<p className="mt-3 text-sm">ملاحظات: {item.notes}</p>}{item.rejectionReason&&<p className="mt-3 text-sm text-red-600">سبب الرفض: {item.rejectionReason}</p>}{item.status==='PENDING'&&<div className="mt-5 grid gap-3 sm:grid-cols-2"><form action={reviewAcquisitionApplicationAction}><input type="hidden" name="applicationId" value={item.id}/><input type="hidden" name="decision" value="APPROVE"/><button className="w-full rounded-xl bg-emerald-600 px-4 py-2.5 font-bold text-white">قبول مبدئي</button></form><form action={reviewAcquisitionApplicationAction} className="flex gap-2"><input type="hidden" name="applicationId" value={item.id}/><input type="hidden" name="decision" value="REJECT"/><input name="reason" required maxLength={500} placeholder="سبب الرفض" className="min-w-0 flex-1 rounded-xl border bg-transparent p-2.5"/><button className="rounded-xl bg-red-600 px-4 font-bold text-white">رفض</button></form></div>}</article>)}{!applications.length&&<p className="rounded-2xl border border-dashed p-12 text-center text-[var(--muted-foreground)]">لا توجد طلبات حتى الآن.</p>}</section>
    <section><h2 className="mb-3 text-xl font-black">توثيق هويات المسوّقين ({verifications.length})</h2><div className="space-y-3">{verifications.map(item=><article key={item.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black">{item.marketerAccount.user.name}</h3><p className="text-sm text-[var(--muted-foreground)]">{item.legalName} · {item.documentType === 'PASSPORT' ? 'جواز سفر' : 'بطاقة هوية'} · {item.documents.length} مستند</p></div><b>{item.status}</b></div><div className="mt-3 flex flex-wrap gap-2">{item.documents.map(document=><a key={document.id} target="_blank" rel="noreferrer" href={`/api/marketer/identity-documents/${document.id}`} className="rounded-lg border px-3 py-2 text-sm font-bold">فتح {document.fileName}</a>)}</div>{item.status==='PENDING'&&<div className="mt-4 grid gap-2 md:grid-cols-2"><form action={reviewMarketerIdentityAction}><input type="hidden" name="verificationId" value={item.id}/><input type="hidden" name="decision" value="APPROVE"/><button className="w-full rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white">اعتماد الهوية</button></form><form action={reviewMarketerIdentityAction} className="flex gap-2"><input type="hidden" name="verificationId" value={item.id}/><input type="hidden" name="decision" value="REJECT"/><input name="reason" required placeholder="سبب الرفض" className="min-w-0 flex-1 rounded-lg border p-2"/><button className="rounded-lg bg-red-600 px-4 py-2 text-white">رفض</button></form></div>}</article>)}{!verifications.length&&<p className="rounded-2xl border border-dashed p-6 text-center text-[var(--muted-foreground)]">لا توجد طلبات توثيق بعد.</p>}</div></section>
    <section><h2 className="mb-3 text-xl font-black">إحالات التجار عبر المسوّقين ({referrals.length})</h2><div className="space-y-3">{referrals.map(item=><article key={item.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black">{item.marketerAccount.user.name}</h3><p className="text-sm text-[var(--muted-foreground)]">التاجر: {item.referredMerchant.name} · {item.codeSnapshot}</p></div><b>{item.status}</b></div></article>)}{!referrals.length&&<p className="rounded-2xl border border-dashed p-6 text-center text-[var(--muted-foreground)]">لا توجد إحالات تجار حتى الآن.</p>}</div></section>
    <section><h2 className="mb-3 text-xl font-black">عمولات اشتراكات المسوّقين ({commissions.length})</h2><div className="space-y-3">{commissions.map(item=><article key={item.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black">{item.marketerAccount.user.name}</h3><p className="text-sm text-[var(--muted-foreground)]">عن اشتراك {item.referralRecord.referredMerchant.name} · {item.commissionRate.toString()}%</p></div><b>{item.amount.toString()} {item.currency} · {item.status}</b></div><p className="mt-2 text-xs text-[var(--muted-foreground)]">فترة التعليق حتى: {item.holdUntil.toLocaleString('ar-SD')}</p></article>)}{!commissions.length&&<p className="rounded-2xl border border-dashed p-6 text-center text-[var(--muted-foreground)]">لا توجد عمولات اشتراك حتى الآن.</p>}</div></section>
  </div>;
}
