import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getMerchantByIdAction, updateMerchantStatusAction } from '@/modules/admin/actions';
import { PLATFORM_PERMISSIONS, hasPlatformPermission, requirePlatformPermission } from '@/lib/platform-permissions';
import { MerchantEntitlementsEditor } from '@/components/admin/merchant-entitlements-editor';
import { getMerchantPlanSnapshot } from '@/modules/merchant-subscriptions';

type MerchantDetail = { id:string; name:string; slug:string; status:string; businessType:string; email:string|null; phone:string|null; createdAt:Date; users:Array<{isOwner:boolean;role:string;user:{id:string;name:string|null;email:string;phone:string|null}}>; subscription:{status:string;entitlementOverrides:unknown;plan:{name:string;code:string}}|null; storefrontSettings:{isPublished:boolean}|null; _count:{products:number;orders:number;customers:number;branches:number}; orders:Array<{id:string;orderNumber:string;status:string;total:number;createdAt:Date}>; orderStatusCounts:Array<{status:string;count:number}> };
const orderLabels: Record<string, string> = { NEW: 'جديد', ACCEPTED: 'مقبول', PREPARING: 'قيد التجهيز', READY: 'جاهز', OUT_FOR_DELIVERY: 'جاري التوصيل', DELIVERED: 'تم التوصيل', CANCELLED: 'ملغي', REJECTED: 'مرفوض' };
const orderStyle: Record<string, string> = { NEW: 'bg-sky-50 text-sky-700', ACCEPTED: 'bg-indigo-50 text-indigo-700', PREPARING: 'bg-amber-50 text-amber-800', READY: 'bg-violet-50 text-violet-700', OUT_FOR_DELIVERY: 'bg-blue-50 text-blue-700', DELIVERED: 'bg-emerald-50 text-emerald-700', CANCELLED: 'bg-slate-100 text-slate-700', REJECTED: 'bg-red-50 text-red-700' };

export default async function MerchantDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const actor = await requirePlatformPermission(PLATFORM_PERMISSIONS.MERCHANTS_READ);
  const { id } = await params;
  const result = await getMerchantByIdAction(id);
  if (!result.success) notFound();
  const merchant = result.data as MerchantDetail;
  const canManage = hasPlatformPermission(actor.role, PLATFORM_PERMISSIONS.MERCHANTS_MANAGE);
  const canManageSubscriptions = hasPlatformPermission(actor.role, PLATFORM_PERMISSIONS.SUBSCRIPTIONS_MANAGE);
  const effectivePlan = canManageSubscriptions ? await getMerchantPlanSnapshot(merchant.id) : null;
  const publicStoreUrl = `/store/${merchant.slug}`;

  return <div className="space-y-7" dir="rtl">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link href="/admin/merchants" className="text-xs font-bold text-[var(--primary)]">← جميع التجار</Link><h1 className="mt-2 text-2xl font-black">{merchant.name}</h1><p className="text-sm text-[var(--muted-foreground)]">{merchant.slug} · {merchant.businessType}</p><a href={publicStoreUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex rounded-lg border border-[var(--primary)] px-3 py-1.5 text-xs font-bold text-[var(--primary)]">فتح واجهة المتجر ↗</a></div><span className="w-fit rounded-full bg-[var(--muted)] px-3 py-1.5 text-xs font-black">{merchant.status}</span></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['المنتجات', merchant._count.products], ['إجمالي الطلبات', merchant._count.orders], ['العملاء', merchant._count.customers], ['الفروع', merchant._count.branches]].map(([label, value]) => <Stat key={String(label)} label={String(label)} value={Number(value)}/>)}</div>
    <section className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">حالات الطلبات والتوصيل</h2><p className="mt-1 text-xs text-[var(--muted-foreground)]">مؤشرات تشغيلية ومحاسبية تصبح أساس مطابقة حالات شركة التوصيل لاحقاً.</p></div><a href={publicStoreUrl} target="_blank" rel="noreferrer" className="text-sm font-bold text-[var(--primary)]">رابط المتجر</a></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.keys(orderLabels).map(status => <div key={status} className="rounded-xl border border-[var(--border)] p-4"><p className="text-xs text-[var(--muted-foreground)]">{orderLabels[status]}</p><p className="mt-2 text-2xl font-black">{merchant.orderStatusCounts.find(item => item.status === status)?.count ?? 0}</p></div>)}</div></section>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5"><h2 className="font-bold">الحساب والاشتراك</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Info label="البريد" value={merchant.email ?? '—'}/><Info label="الهاتف" value={merchant.phone ?? '—'}/><Info label="رابط المتجر" value={publicStoreUrl}/><Info label="الباقة" value={merchant.subscription?.plan.name ?? 'الأساسية'}/><Info label="حالة الاشتراك" value={merchant.subscription?.status ?? '—'}/><Info label="المتجر منشور" value={merchant.storefrontSettings?.isPublished ? 'نعم' : 'لا'}/><Info label="تاريخ الانضمام" value={new Date(merchant.createdAt).toLocaleDateString('ar-SD')}/></dl></section><section className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5"><h2 className="font-bold">مالكو وموظفو المتجر</h2><div className="mt-4 divide-y divide-[var(--border)]">{merchant.users.map(member => <div key={member.user.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-bold">{member.user.name ?? member.user.email}</p><p className="text-xs text-[var(--muted-foreground)]">{member.user.email}</p></div><span className="text-xs font-semibold">{member.isOwner ? 'OWNER' : member.role}</span></div>)}</div></section></div>
    <section className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5"><h2 className="font-bold">آخر الطلبات</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="border-b border-[var(--border)] text-[var(--muted-foreground)]"><tr>{['رقم الطلب','الحالة','الإجمالي','التاريخ'].map(label => <th key={label} className="p-3 text-right">{label}</th>)}</tr></thead><tbody>{merchant.orders.map(order => <tr key={order.id} className="border-b border-[var(--border)] last:border-0"><td className="p-3 font-mono">{order.orderNumber}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${orderStyle[order.status] ?? 'bg-slate-100'}`}>{orderLabels[order.status] ?? order.status}</span></td><td className="p-3">{order.total}</td><td className="p-3 text-xs">{new Date(order.createdAt).toLocaleDateString('ar-SD')}</td></tr>)}{!merchant.orders.length && <tr><td colSpan={4} className="p-8 text-center text-[var(--muted-foreground)]">لا توجد طلبات بعد.</td></tr>}</tbody></table></div></section>
    {canManage && <section className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5"><h2 className="font-bold">إجراءات تشغيلية</h2><p className="mt-1 text-xs text-[var(--muted-foreground)]">الإيقاف يمنع تشغيل المتجر ولا يحذف بياناته.</p><div className="mt-4 flex flex-wrap gap-2">{(['ACTIVE', 'SUSPENDED', 'CLOSED'] as const).map(status => <form key={status} action={updateMerchantStatusAction}><input type="hidden" name="merchantId" value={merchant.id}/><input type="hidden" name="status" value={status}/><button disabled={merchant.status === status} className={`rounded-xl px-4 py-2 text-sm font-bold disabled:opacity-40 ${status === 'ACTIVE' ? 'bg-emerald-600 text-white' : status === 'SUSPENDED' ? 'bg-amber-500 text-white' : 'border border-red-300 text-red-700'}`}>{status}</button></form>)}</div></section>}
    {canManageSubscriptions && effectivePlan && <MerchantEntitlementsEditor merchantId={merchant.id} entitlements={effectivePlan.entitlements} hasOverrides={merchant.subscription?.entitlementOverrides != null}/>}</div>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5"><p className="text-xs text-[var(--muted-foreground)]">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-[var(--muted-foreground)]">{label}</dt><dd className="mt-1 break-all font-semibold">{value}</dd></div>; }
