'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { signIn } from 'next-auth/react';
import { InternationalPhoneInput } from '@/components/ui/international-phone-input';

export default function MarketerRegisterPage() {
  const router = useRouter(); const [countryCode, setCountryCode] = useState('+249'); const [phone, setPhone] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); const payload = { name: form.get('name'), email: form.get('email'), password: form.get('password'), phone, countryCode }; try { const response = await fetch('/api/auth/register-marketer', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'تعذر إنشاء الحساب'); return; } const login = await signIn('credentials', { email: String(payload.email), password: String(payload.password), redirect: false }); router.replace(login?.error ? '/login' : '/marketer'); } catch { setError('تعذر الاتصال. حاول مرة أخرى.'); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-slate-50 px-4 py-10" dir="rtl"><form onSubmit={submit} className="mx-auto max-w-lg space-y-5 rounded-3xl border bg-white p-7 shadow-sm"><div><p className="font-bold text-emerald-700">وصلة · شركاء النمو</p><h1 className="mt-2 text-2xl font-black">أنشئ حساب المسوّق</h1><p className="mt-2 text-sm leading-6 text-slate-600">حساب واحد للتسويق لعدة متاجر ومتابعة كل العمولات.</p></div><Field name="name" label="الاسم الكامل" required/><Field name="email" label="البريد الإلكتروني" type="email" required/><label className="block text-sm font-bold">رقم واتساب<div className="mt-2"><InternationalPhoneInput countryCode={countryCode} phone={phone} onCountryCodeChange={setCountryCode} onPhoneChange={setPhone} required disabled={loading}/></div></label><Field name="password" label="كلمة المرور" type="password" minLength={8} required/>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-[#087d82] px-5 py-3 font-bold text-white disabled:opacity-50">{loading ? 'جارٍ الإنشاء...' : 'إنشاء الحساب'}</button></form></main>;
}
function Field({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="block text-sm font-bold">{label}<input {...props} className="mt-2 w-full rounded-xl border p-3"/></label>; }
