import { PLATFORM_PERMISSIONS, requirePlatformPermission } from '@/lib/platform-permissions';
import { getAdminReferralDashboard } from '@/modules/merchant-referrals/merchant-referrals.service';
import { reviewReferralCommissionAction, reviewReferralRewardAction, updateReferralProgramAction } from '@/modules/merchant-referrals/actions';

export const dynamic = 'force-dynamic';
const rewardNames: Record<string,string> = { PRO_DAYS: 'أيام Pro', AI_CREDITS: 'رصيد AI', ACCOUNT_CREDIT: 'رصيد حساب', CASH: 'نقدي' };

export default async function AdminReferralsPage() {
  const actor = await requirePlatformPermission(PLATFORM_PERMISSIONS.FINANCE_READ);
  const { program, referrals, rewards, commissions } = await getAdminReferralDashboard();
  const canConfigure = actor.role === 'PLATFORM_OWNER' || actor.role === 'PLATFORM_ADMIN';
  return <div className="space-y-7" dir="rtl">
    <header><h1 className="text-2xl font-black">برنامج إحالة تجار وصلة</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">إعداد التأهل، مراجعة الإحالات وتنفيذ المكافآت يدوياً مع سجل ثابت.</p></header>
    <section className="rounded-2xl border bg-[var(--card)] p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="font-black">إعداد البرنامج</h2><p className="text-sm text-[var(--muted-foreground)]">الحالة: {program.isActive ? 'مفعّل' : 'موقوف'}</p></div></div>{canConfigure ? <form action={updateReferralProgramAction} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <label className="text-sm">شرط التأهل<select name="qualificationRule" defaultValue="FIRST_PAID_PRO" className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5"><option value="FIRST_PAID_PRO">أول اشتراك Pro مدفوع</option></select></label>
      <label className="text-sm">نوع المكافأة<select name="rewardType" defaultValue={program.rewardType} className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5">{Object.entries(rewardNames).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <label className="text-sm">قيمة المكافأة<input name="rewardValue" type="number" min="0" step="0.01" defaultValue={program.rewardValue.toString()} className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5" /></label>
      <label className="text-sm">العملة للجوائز المالية<input name="currency" maxLength={6} defaultValue={program.currency ?? 'SDG'} className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5 uppercase" /></label>
      <label className="text-sm">مدة التعليق بالأيام<input name="holdDays" type="number" min="0" max="180" defaultValue={program.holdDays} className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5" /></label>
      <label className="text-sm">نسبة العمولة %<input name="commissionRate" type="number" min="0.01" max="100" step="0.01" defaultValue={program.commissionRate.toString()} className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5" /></label>
      <label className="text-sm">مدة العمولة بالشهور<input name="commissionMonths" type="number" min="1" max="24" defaultValue={program.commissionMonths} className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5" /></label>
      <label className="text-sm">الحد الأدنى للسداد<input name="minimumPayout" type="number" min="0" step="0.01" defaultValue={program.minimumPayout.toString()} className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5" /></label>
      <label className="text-sm md:col-span-2 xl:col-span-3">الشروط<textarea name="terms" maxLength={2000} rows={3} defaultValue={program.terms ?? ''} className="mt-1 w-full rounded-lg border bg-[var(--background)] p-2.5" /></label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" value="true" defaultChecked={program.isActive}/> تفعيل البرنامج للإحالات الجديدة</label><button className="rounded-xl bg-[var(--primary)] px-5 py-3 font-bold text-white md:col-span-2 xl:col-span-3">حفظ السياسة</button>
    </form> : <p className="mt-4 text-sm">إعداد السياسة متاح للمالك أو مدير المنصة فقط.</p>}</section>
    <section><h2 className="mb-3 font-black">الإحالات الأخيرة ({referrals.length})</h2><div className="overflow-x-auto rounded-2xl border bg-[var(--card)]"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[var(--muted)]"><tr>{['المُحيل','المتجر الجديد','الرمز','الحالة','تاريخ التسجيل'].map(x=><th key={x} className="p-3 text-right">{x}</th>)}</tr></thead><tbody>{referrals.map(item=><tr key={item.id} className="border-t"><td className="p-3 font-bold">{item.referrerMerchant.name}</td><td className="p-3">{item.status === 'REJECTED' ? 'محجوب للخصوصية' : item.referredMerchant.name}</td><td className="p-3 font-mono">{item.codeSnapshot}</td><td className="p-3">{item.status}{item.rejectionReason ? ` · ${item.rejectionReason}` : ''}</td><td className="p-3">{item.registeredAt.toLocaleString('ar-SD')}</td></tr>)}{!referrals.length&&<tr><td colSpan={5} className="p-10 text-center">لا توجد إحالات.</td></tr>}</tbody></table></div></section>
    <section><h2 className="mb-3 font-black">المكافآت ({rewards.length})</h2><div className="space-y-3">{rewards.map(reward=><article key={reward.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{reward.referrerMerchant.name}</h3><p className="text-sm text-[var(--muted-foreground)]">عن إحالة {reward.referralRecord.referredMerchant.name}</p></div><p className="font-bold">{reward.value.toString()} {rewardNames[reward.type]} {reward.currency ?? ''} · {reward.status}</p></div><p className="mt-2 text-xs">تنتهي فترة التعليق: {reward.holdUntil.toLocaleString('ar-SD')}</p>{reward.status==='PENDING'&&<div className="mt-4 grid gap-2 md:grid-cols-2"><form action={reviewReferralRewardAction}><input type="hidden" name="rewardId" value={reward.id}/><input type="hidden" name="decision" value="APPROVE"/><button className="w-full rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white">اعتماد بعد انتهاء التعليق</button></form><form action={reviewReferralRewardAction} className="flex gap-2"><input type="hidden" name="rewardId" value={reward.id}/><input type="hidden" name="decision" value="REJECT"/><input name="note" required maxLength={500} placeholder="سبب الرفض" className="min-w-0 flex-1 rounded-lg border p-2"/><button className="rounded-lg bg-red-600 px-4 py-2 font-bold text-white">رفض</button></form></div>}{reward.status==='APPROVED'&&<form action={reviewReferralRewardAction} className="mt-4 flex gap-2"><input type="hidden" name="rewardId" value={reward.id}/><input type="hidden" name="decision" value="FULFILL"/><input name="fulfillmentRef" required maxLength={120} placeholder="مرجع التحويل أو منح الرصيد" className="min-w-0 flex-1 rounded-lg border p-2"/><button className="rounded-lg bg-[var(--primary)] px-4 py-2 font-bold text-white">تأكيد التنفيذ</button></form>}</article>)}{!rewards.length&&<p className="rounded-2xl border border-dashed p-10 text-center">لا توجد مكافآت مستحقة.</p>}</div></section>
    <section><h2 className="mb-3 font-black">عمولات الاشتراكات المتكررة ({commissions.length})</h2><div className="space-y-3">{commissions.map(commission => <article key={commission.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{commission.referrerMerchant.name}</h3><p className="text-sm text-[var(--muted-foreground)]">عن اشتراك {commission.referralRecord.referredMerchant.name} · {commission.commissionRate.toString()}%</p></div><p className="font-black">{commission.amount.toString()} {commission.currency} · {commission.status}</p></div><p className="mt-2 text-xs">قيمة الاشتراك: {commission.grossAmount.toString()} · نهاية التعليق: {commission.holdUntil.toLocaleString('ar-SD')}</p>{commission.status === 'PENDING' && <div className="mt-4 grid gap-2 md:grid-cols-2"><form action={reviewReferralCommissionAction}><input type="hidden" name="commissionId" value={commission.id}/><input type="hidden" name="decision" value="APPROVE"/><button className="w-full rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white">اعتماد</button></form><form action={reviewReferralCommissionAction} className="flex gap-2"><input type="hidden" name="commissionId" value={commission.id}/><input type="hidden" name="decision" value="REJECT"/><input name="note" required maxLength={500} placeholder="سبب الرفض" className="min-w-0 flex-1 rounded-lg border p-2"/><button className="rounded-lg bg-red-600 px-4 py-2 font-bold text-white">رفض</button></form></div>}{commission.status === 'APPROVED' && <form action={reviewReferralCommissionAction} className="mt-4 flex gap-2"><input type="hidden" name="commissionId" value={commission.id}/><input type="hidden" name="decision" value="FULFILL"/><input name="fulfillmentRef" required maxLength={120} placeholder="مرجع التحويل" className="min-w-0 flex-1 rounded-lg border p-2"/><button className="rounded-lg bg-[var(--primary)] px-4 py-2 font-bold text-white">سداد الرصيد المعتمد</button></form>}</article>)}{!commissions.length && <p className="rounded-2xl border border-dashed p-10 text-center">لا توجد عمولات اشتراك.</p>}</div></section>
  </div>;
}
