import { PLATFORM_PERMISSIONS, requirePlatformPermission } from '@/lib/platform-permissions';
import { listIdentityVerificationsForAdmin } from '@/modules/identity-verification/identity-verification.service';
import { reviewIdentityVerificationAction } from '@/modules/identity-verification/actions';

export const dynamic = 'force-dynamic';
const statuses: Record<string, string> = { DRAFT: 'مسودة', PENDING: 'قيد المراجعة', APPROVED: 'موثّق', REJECTED: 'مرفوض', EXPIRED: 'منتهي' };

export default async function AdminVerificationsPage() {
  await requirePlatformPermission(PLATFORM_PERMISSIONS.MERCHANTS_MANAGE);
  const { merchants, affiliates } = await listIdentityVerificationsForAdmin();
  return <div className="space-y-7" dir="rtl"><header><h1 className="text-2xl font-black">مراجعة الهوية KYC</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">راجع الوثيقة وتاريخ سريانها والاسم قبل الاعتماد. المستندات خاصة ولا تُرسل عبر روابط عامة.</p></header><VerificationList title="هويات التجار" kind="MERCHANT" items={merchants.map(item => ({ ...item, subject: item.merchant.name, context: item.merchant.slug, payout: null }))}/><VerificationList title="هويات المسوّقين" kind="AFFILIATE" items={affiliates.map(item => ({ ...item, subject: item.affiliate.name, context: `${item.merchant.name} · ${item.affiliate.code}`, payout: item.affiliate.payoutProfile }))}/></div>;
}

type Item = { id: string; subject: string; context: string; legalName: string; documentType: string; expiresAt: Date; status: string; rejectionReason: string | null; documents: Array<{ id: string; side: string; fileName: string }>; payout: { method: string; bankName: string | null; accountName: string; accountNumber: string; iban: string | null } | null };

function VerificationList({ title, kind, items }: { title: string; kind: 'MERCHANT' | 'AFFILIATE'; items: Item[] }) {
  return <section><h2 className="mb-3 font-black">{title} ({items.length})</h2><div className="space-y-4">{items.map(item => <article key={item.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-black">{item.subject}</h3><p className="text-xs text-[var(--muted-foreground)]">{item.context}</p></div><span className="rounded-full bg-[var(--muted)] px-3 py-1 text-xs font-bold">{statuses[item.status] ?? item.status}</span></div><dl className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><dt className="text-[var(--muted-foreground)]">الاسم القانوني</dt><dd className="font-bold">{item.legalName}</dd></div><div><dt className="text-[var(--muted-foreground)]">الوثيقة</dt><dd>{item.documentType === 'PASSPORT' ? 'جواز سفر' : 'بطاقة هوية'}</dd></div><div><dt className="text-[var(--muted-foreground)]">الانتهاء</dt><dd className={item.expiresAt <= new Date() ? 'font-bold text-red-700' : 'font-bold'}>{item.expiresAt.toLocaleDateString('ar-SD')}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{item.documents.map(document => <a key={document.id} href={`/api/identity-documents/${document.id}?kind=${kind}`} target="_blank" rel="noreferrer" className="rounded-lg border px-3 py-2 text-sm font-bold">عرض {document.side === 'FRONT' ? 'الأمام' : 'الخلف'}</a>)}</div>{item.payout && <p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">السداد: {item.payout.method} · {item.payout.accountName} · {item.payout.accountNumber}{item.payout.iban ? ` · ${item.payout.iban}` : ''}</p>}{item.rejectionReason && <p className="mt-3 text-sm text-red-700">{item.rejectionReason}</p>}{item.status === 'PENDING' && <div className="mt-5 grid gap-2 md:grid-cols-2"><form action={reviewIdentityVerificationAction}><input type="hidden" name="kind" value={kind}/><input type="hidden" name="verificationId" value={item.id}/><input type="hidden" name="decision" value="APPROVE"/><button className="w-full rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">اعتماد الهوية</button></form><form action={reviewIdentityVerificationAction} className="flex gap-2"><input type="hidden" name="kind" value={kind}/><input type="hidden" name="verificationId" value={item.id}/><input type="hidden" name="decision" value="REJECT"/><input name="reason" required maxLength={500} placeholder="سبب الرفض" className="min-w-0 flex-1 rounded-xl border p-2"/><button className="rounded-xl bg-red-600 px-4 py-2 font-bold text-white">رفض</button></form></div>}</article>)}{!items.length && <p className="rounded-2xl border border-dashed p-8 text-center text-[var(--muted-foreground)]">لا توجد طلبات.</p>}</div></section>;
}
