ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATFORM_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATFORM_OPERATIONS';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATFORM_FINANCE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATFORM_SUPPORT';

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "platformAccessEnabled" BOOLEAN NOT NULL DEFAULT false;
UPDATE "users" SET "platformAccessEnabled" = true WHERE "role"::text LIKE 'PLATFORM_%';
