'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ExternalImage } from '@/components/external-image';

type Profile = { durationMinutes: number; bookingRequired: boolean; fulfillmentType: 'AT_BRANCH' | 'AT_CUSTOMER_LOCATION' | 'ONLINE' | 'REQUEST_ONLY'; minimumNoticeMinutes: number; maxParticipants: number; advancePaymentPercent: number; cancellationPolicy: string | null };
const place: Record<Profile['fulfillmentType'], string> = { AT_BRANCH: 'في الفرع', AT_CUSTOMER_LOCATION: 'عند العميل', ONLINE: 'أونلاين', REQUEST_ONLY: 'طلب خدمة' };

export function ServiceBookingClient({ slug, product, branches }: { slug: string; product: { name: string; slug: string; description: string | null; images: string[]; price: number; serviceProfile: Profile }; branches: { id: string; name: string; address: string | null }[] }) {
  const profile = product.serviceProfile;
  const [pending, setPending] = useState(false); const [result, setResult] = useState<string | null>(null); const [error, setError] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setError('');
    const form = new FormData(event.currentTarget);
    const start = String(form.get('startAt') || '');
    const payload = { customerName: String(form.get('customerName')), customerPhone: String(form.get('customerPhone')), branchId: String(form.get('branchId') || '') || undefined, startAt: start ? new Date(start).toISOString() : undefined, participantCount: Number(form.get('participants') || 1), note: String(form.get('note') || '') || undefined, customerAddress: String(form.get('customerAddress') || '') || undefined };
    try { const response = await fetch(`/api/store/${slug}/services/${product.slug}/book`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data.orderNumber); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر إرسال الطلب'); } finally { setPending(false); }
  }
  if (result) return <main dir="rtl" className="mx-auto flex min-h-screen max-w-xl items-center p-5"><section className="w-full rounded-3xl border bg-white p-8 text-center shadow-sm"><div className="text-5xl">✓</div><h1 className="mt-4 text-2xl font-black">تم إرسال طلب الخدمة</h1><p className="mt-2 text-slate-600">رقم طلبك: <b dir="ltr">{result}</b>. سيؤكد المتجر الموعد وطريقة السداد قريباً.</p><Link className="mt-6 inline-block rounded-xl bg-teal-600 px-5 py-3 font-bold text-white" href={`/store/${slug}`}>العودة للمتجر</Link></section></main>;
  return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-2xl"><Link href={`/store/${slug}`} className="text-sm font-bold text-teal-700">← العودة للمتجر</Link><section className="mt-4 overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="grid sm:grid-cols-[.8fr_1.2fr]">{product.images[0] ? <div className="relative min-h-48 bg-slate-100"><ExternalImage src={product.images[0]} alt={product.name} fill className="object-contain p-4" /></div> : <div className="flex min-h-48 items-center justify-center bg-teal-50 text-6xl">🗓️</div>}<div className="p-6"><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-700">خدمة · {place[profile.fulfillmentType]}</span><h1 className="mt-3 text-2xl font-black">{product.name}</h1>{product.description && <p className="mt-2 text-sm leading-6 text-slate-600">{product.description}</p>}<p className="mt-4 text-xl font-black text-teal-700">{product.price.toLocaleString()} SDG</p>{profile.bookingRequired && <p className="mt-1 text-xs text-slate-500">مدة الموعد: {profile.durationMinutes} دقيقة</p>}</div></div>
    <form onSubmit={submit} className="space-y-4 border-t p-6"><h2 className="text-lg font-black">بيانات الطلب</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">الاسم<input required name="customerName" minLength={2} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-bold">رقم الهاتف<input required name="customerPhone" minLength={7} inputMode="tel" dir="ltr" className="mt-1 w-full rounded-xl border p-3 font-normal" /></label></div>{profile.fulfillmentType === 'AT_BRANCH' && <label className="block text-sm font-bold">الفرع<select required name="branchId" className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="">اختر الفرع</option>{branches.map(branch => <option key={branch.id} value={branch.id}>{branch.name}{branch.address ? ` — ${branch.address}` : ''}</option>)}</select></label>}{profile.fulfillmentType === 'AT_CUSTOMER_LOCATION' && <label className="block text-sm font-bold">عنوان تنفيذ الخدمة<textarea required name="customerAddress" rows={2} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label>}{profile.bookingRequired && <label className="block text-sm font-bold">الموعد المطلوب<input required name="startAt" type="datetime-local" min={new Date(Date.now() + profile.minimumNoticeMinutes * 60_000).toISOString().slice(0, 16)} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label>}<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">عدد الأشخاص<input name="participants" type="number" min="1" max={profile.maxParticipants} defaultValue="1" className="mt-1 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-bold">ملاحظات<textarea name="note" rows={1} maxLength={500} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label></div>{profile.advancePaymentPercent > 0 && <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">قد يطلب المتجر عربوناً بنسبة {profile.advancePaymentPercent}% لتأكيد الموعد.</p>}{profile.cancellationPolicy && <p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600"><b>سياسة الإلغاء:</b> {profile.cancellationPolicy}</p>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={pending} className="w-full rounded-xl bg-teal-600 p-3 font-bold text-white disabled:opacity-50">{pending ? 'جارٍ الإرسال…' : profile.bookingRequired ? 'إرسال طلب الحجز' : 'إرسال طلب الخدمة'}</button><p className="text-center text-xs text-slate-500">سيؤكد المتجر الموعد وطريقة السداد قبل بدء الخدمة.</p></form></section></div></main>;
}
