import Link from 'next/link';
import { notFound } from 'next/navigation';
import prisma from '@/lib/db/prisma';
import { PLATFORM_PERMISSIONS, requirePlatformPermission } from '@/lib/platform-permissions';

export const dynamic = 'force-dynamic';
const statusLabel: Record<string, string> = { REGISTERED: 'مسجل', ACTIVATED: 'مفعّل', QUALIFIED: 'مؤهل', REJECTED: 'مرفوض', PENDING: 'معلّقة', APPROVED: 'معتمدة', PAID: 'مدفوعة', FULFILLED: 'مدفوعة' };

export default async function MarketerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePlatformPermission(PLATFORM_PERMISSIONS.MERCHANTS_MANAGE);
  const { id } = await params;
  const marketer = await prisma.marketerAccount.findUnique({ where: { id }, include: { user: { select: { name: true, email: true, phone: true } }, identityVerification: true, payoutProfile: { select: { method: true, bankName: true } }, referrals: { include: { referredMerchant: { select: { id: true, name: true, slug: true, subscription: { include: { plan: { select: { name: true, code: true } } } } } }, commissions: { select: { amount: true, currency: true, status: true } } }, orderBy: { registeredAt: 'desc' } }, commissions: { select: { amount: true, currency: true, status: true, createdAt: true }, orderBy: { createdAt: 'desc' }, take: 10 } } });
  if (!marketer) notFound();
  return <div className="space-y-7" dir="rtl"><header><Link href="/admin/marketers/directory" className="text-xs font-bold text-[var(--primary)]">← دليل المسوّقين</Link><h1 className="mt-2 text-2xl font-black">{marketer.user.name || 'ملف مسوّق'}</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">{marketer.acquisitionCode} · انضم {marketer.createdAt.toLocaleDateString('ar-SD')}</p></header><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['الهاتف', marketer.user.phone || '—'], ['البريد', marketer.user.email], ['حالة الهوية', marketer.identityVerification?.status || 'لم تُرسل'], ['الإحالات', String(marketer.referrals.length)]].map(([label, value])=><div key={label} className="rounded-2xl border bg-[var(--card)] p-5"><p className="text-xs text-[var(--muted-foreground)]">{label}</p><p className="mt-2 break-all font-black">{value}</p></div>)}</section><section className="rounded-2xl border bg-[var(--card)] p-5"><h2 className="font-black">الملف وبيانات السداد</h2><dl className="mt-4 grid gap-4 text-sm md:grid-cols-2"><Item label="المدينة" value={marketer.city || '—'}/><Item label="نبذة" value={marketer.bio || '—'}/><Item label="طريقة السداد" value={marketer.payoutProfile?.method || 'لم تُضف'}/><Item label="البنك/المحفظة" value={marketer.payoutProfile?.bankName || '—'}/></dl></section><section><h2 className="mb-3 font-black">التجار المُحالون</h2><div className="overflow-x-auto rounded-2xl border bg-[var(--card)]"><table className="w-full min-w-[700px] text-sm"><thead className="bg-[var(--muted)]"><tr>{['المتجر','الباقة','حالة الإحالة','العمولات','التاريخ'].map(x=><th key={x} className="p-3 text-right">{x}</th>)}</tr></thead><tbody>{marketer.referrals.map(r=><tr key={r.id} className="border-t"><td className="p-3"><Link className="font-bold text-[var(--primary)] hover:underline" href={`/admin/merchants/${r.referredMerchant.id}`}>{r.referredMerchant.name}</Link><p dir="ltr" className="text-xs text-[var(--muted-foreground)]">{r.referredMerchant.slug}</p></td><td className="p-3">{r.referredMerchant.subscription?.plan.name || 'الأساسية'}</td><td className="p-3">{statusLabel[r.status] || r.status}</td><td className="p-3">{r.commissions.map(c => `${c.amount.toString()} ${c.currency} (${statusLabel[c.status] || c.status})`).join(' · ') || '—'}</td><td className="p-3 text-xs">{r.registeredAt.toLocaleDateString('ar-SD')}</td></tr>)}{!marketer.referrals.length && <tr><td colSpan={5} className="p-10 text-center">لا توجد إحالات تجار بعد.</td></tr>}</tbody></table></div></section></div>;
}
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-[var(--muted-foreground)]">{label}</dt><dd className="mt-1 break-words font-semibold">{value}</dd></div>; }
