import Link from 'next/link';
import { getAuthContext, requirePermission } from '@/lib/permissions';
import { reviewProductApplicationAction } from '@/modules/marketer-applications/actions';
import { listProductApplicationsForMerchant } from '@/modules/marketer-applications/marketer-applications.service';

export const dynamic = 'force-dynamic';
const statusName = { PENDING: 'قيد المراجعة', APPROVED: 'مقبول', REJECTED: 'مرفوض' } as const;

export default async function AffiliateApplicationsPage() {
  const auth = await getAuthContext();
  requirePermission(auth, 'settings:read');
  const canReview = auth.role === 'MERCHANT_OWNER' || auth.permissions.includes('settings:update');
  const applications = await listProductApplicationsForMerchant(auth.merchantId);
  return <div className="space-y-7" dir="rtl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-[var(--primary)]">التسويق بالعمولة</p><h1 className="mt-2 text-2xl font-black">طلبات انضمام المسوقين</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">راجع الجمهور والخبرة قبل القبول. عند القبول يُنشأ المسوّق داخل متجرك ثم ترسل له رابط KYC والسداد.</p></div><Link href="/dashboard/affiliates" className="rounded-xl border px-4 py-2 text-sm font-bold">إدارة البرنامج</Link></header>
    <section className="grid gap-4">{applications.map(item=><article key={item.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black">{item.name}</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]" dir="ltr">{item.phone} · {item.email}</p><p className="mt-1 text-sm">{item.city} · {item.channels.join('، ')}</p></div><span className="rounded-full bg-[var(--muted)] px-3 py-1 text-xs font-bold">{statusName[item.status]}</span></div>{item.experience&&<p className="mt-4 rounded-xl bg-[var(--muted)] p-3 text-sm leading-6">{item.experience}</p>}<div className="mt-3 flex flex-wrap gap-4 text-xs text-[var(--muted-foreground)]"><span>الجمهور: {item.audienceSize?.toLocaleString('ar-SD')??'غير محدد'}</span>{item.portfolioUrl&&<a href={item.portfolioUrl} target="_blank" rel="noreferrer" className="text-[var(--primary)] underline">رابط الأعمال</a>}<span>{item.createdAt.toLocaleString('ar-SD')}</span></div>{item.affiliate&&<p className="mt-3 text-sm text-emerald-700">تم إنشاء المسوّق · KYC: {item.affiliate.identityVerification?.status??'لم يبدأ'}</p>}{item.rejectionReason&&<p className="mt-3 text-sm text-red-600">سبب الرفض: {item.rejectionReason}</p>}{canReview&&item.status==='PENDING'&&<div className="mt-5 grid gap-3 sm:grid-cols-2"><form action={reviewProductApplicationAction}><input type="hidden" name="applicationId" value={item.id}/><input type="hidden" name="decision" value="APPROVE"/><button className="w-full rounded-xl bg-emerald-600 px-4 py-2.5 font-bold text-white">قبول وإنشاء مسوّق</button></form><form action={reviewProductApplicationAction} className="flex gap-2"><input type="hidden" name="applicationId" value={item.id}/><input type="hidden" name="decision" value="REJECT"/><input name="reason" required maxLength={500} placeholder="سبب الرفض" className="min-w-0 flex-1 rounded-xl border bg-transparent p-2.5"/><button className="rounded-xl bg-red-600 px-4 font-bold text-white">رفض</button></form></div>}</article>)}{!applications.length&&<p className="rounded-2xl border border-dashed p-12 text-center text-[var(--muted-foreground)]">لا توجد طلبات. فعّل برنامجك ليظهر متجرك في صفحة تسجيل المسوقين.</p>}</section>
  </div>;
}
