import { PLATFORM_PERMISSIONS, requirePlatformPermission } from '@/lib/platform-permissions';
import { listMerchantDomainsForAdmin } from '@/modules/merchant-domains/merchant-domains.service';
import { reviewMerchantDomainAction } from '@/modules/merchant-domains/actions';

export const dynamic = 'force-dynamic';

export default async function AdminDomainsPage() {
  await requirePlatformPermission(PLATFORM_PERMISSIONS.MERCHANTS_MANAGE);
  const domains = await listMerchantDomainsForAdmin();
  return <div className="space-y-6" dir="rtl"><header><h1 className="text-2xl font-black">دومينات المتاجر</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">فعّل النطاق فقط بعد ظهور VERIFIED وإضافته إلى توجيه Dokploy ونجاح شهادة SSL. الإيقاف يعيد الزائر إلى عدم استخدام الربط المخصص ولا يحذف متجر وصلة.</p></header><div className="space-y-4">{domains.map(domain => <article key={domain.id} className="rounded-2xl border bg-[var(--card)] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">{domain.merchant.name}</h2><p dir="ltr" className="text-left font-mono text-sm">{domain.hostname}</p><p className="text-xs text-[var(--muted-foreground)]">/{domain.merchant.slug} · {domain.merchant.subscription?.plan.code ?? 'FREE'}</p></div><span className="text-sm font-bold">{domain.status}</span></div>{domain.rejectionReason && <p className="mt-3 text-sm text-red-700">{domain.rejectionReason}</p>}<div className="mt-4 flex flex-wrap gap-2">{domain.status === 'VERIFIED' && <form action={reviewMerchantDomainAction}><input type="hidden" name="domainId" value={domain.id}/><input type="hidden" name="decision" value="ACTIVATE"/><button className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">تأكيد التوجيه وSSL وتفعيل</button></form>}{domain.status === 'ACTIVE' && <form action={reviewMerchantDomainAction}><input type="hidden" name="domainId" value={domain.id}/><input type="hidden" name="decision" value="DISABLE"/><button className="rounded-xl border px-4 py-2 font-bold">إيقاف</button></form>}{domain.status !== 'ACTIVE' && <form action={reviewMerchantDomainAction} className="flex gap-2"><input type="hidden" name="domainId" value={domain.id}/><input type="hidden" name="decision" value="REJECT"/><input name="reason" required maxLength={500} placeholder="سبب الرفض" className="rounded-xl border p-2"/><button className="rounded-xl bg-red-600 px-4 py-2 font-bold text-white">رفض</button></form>}</div></article>)}{!domains.length && <p className="rounded-2xl border border-dashed p-8 text-center">لا توجد طلبات ربط.</p>}</div></div>;
}
