import Link from 'next/link';
import { getAuthContext, requirePermission } from '@/lib/permissions';
import { getMerchantDomainDashboard } from '@/modules/merchant-domains/merchant-domains.service';
import { requestMerchantDomainAction, verifyMerchantDomainDnsAction } from '@/modules/merchant-domains/actions';

export const dynamic = 'force-dynamic';
const statuses: Record<string, string> = { PENDING_DNS: 'بانتظار DNS', VERIFIED: 'تم التحقق وينتظر تفعيل وصلة', ACTIVE: 'نشط', REJECTED: 'مرفوض', DISABLED: 'موقوف' };

export default async function MerchantDomainsPage() {
  const auth = await getAuthContext();
  requirePermission(auth, 'settings:read');
  const { domain, available, cnameTarget } = await getMerchantDomainDashboard(auth.merchantId);
  const canEdit = auth.role === 'MERCHANT_OWNER' || auth.permissions.includes('settings:update');
  if (!available) return <div className="mx-auto max-w-2xl rounded-2xl border bg-[var(--card)] p-8 text-center" dir="rtl"><div className="text-4xl">🌐</div><h1 className="mt-4 text-2xl font-black">الدومين الخاص ضمن باقة Pro</h1><p className="mt-2 text-sm leading-7 text-[var(--muted-foreground)]">يبقى متجرك متاحاً على رابط وصلة في الباقة المجانية. Pro يتيح ربط نطاقك مع تحقق ملكية DNS وتفعيل SSL.</p><Link href="/dashboard/subscription" className="mt-6 inline-block rounded-xl bg-[var(--primary)] px-6 py-3 font-bold text-white">عرض باقة Pro</Link></div>;
  return <div className="mx-auto max-w-4xl space-y-6" dir="rtl"><header><p className="font-bold text-[var(--primary)]">باقة Pro</p><h1 className="mt-2 text-2xl font-black">ربط دومين خاص</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">أدخل النطاق بدون https. لن يتغير رابط متجر وصلة حتى ينجح DNS ثم يراجع فريق وصلة التوجيه وSSL.</p></header><section className="rounded-2xl border bg-[var(--card)] p-6">{domain ? <div className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 dir="ltr" className="text-left text-xl font-black">{domain.hostname}</h2><p className="text-sm text-[var(--muted-foreground)]">{statuses[domain.status] ?? domain.status}</p></div>{domain.status === 'ACTIVE' && <a href={`https://${domain.hostname}`} target="_blank" rel="noreferrer" className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white">فتح المتجر</a>}</div>{domain.rejectionReason && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-800">{domain.rejectionReason}</p>}<div className="rounded-xl bg-slate-50 p-5"><h3 className="font-black">سجلات DNS المطلوبة</h3><div className="mt-3 overflow-x-auto text-sm" dir="ltr"><p><b>CNAME</b> @ or www → <code>{cnameTarget}</code></p><p className="mt-2"><b>TXT</b> _wasla-verification → <code>wasla-verification={domain.verificationToken}</code></p></div></div>{canEdit && domain.status !== 'ACTIVE' && <form action={verifyMerchantDomainDnsAction}><button className="rounded-xl bg-[var(--primary)] px-5 py-3 font-bold text-white">فحص سجل التحقق الآن</button></form>}</div> : <p className="text-sm text-[var(--muted-foreground)]">لم تربط نطاقاً بعد.</p>}{canEdit && domain?.status !== 'ACTIVE' && <form action={requestMerchantDomainAction} className="mt-6 flex flex-col gap-3 sm:flex-row"><input name="hostname" required maxLength={253} placeholder="shop.example.com" dir="ltr" className="min-w-0 flex-1 rounded-xl border bg-[var(--background)] p-3"/><button className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">{domain ? 'استبدال النطاق والرمز' : 'بدء الربط'}</button></form>}</section></div>;
}
