import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/lib/auth/config';
import { getMarketerPortal } from '@/modules/marketer-portal/marketer-portal.service';

export const dynamic = 'force-dynamic';
export default async function MarketerPortalPage() {
  const session = await auth();
  if (!session?.user?.id || session.user.role !== 'MARKETER') redirect('/login');
  const data = await getMarketerPortal(session.user.id).catch(() => null);
  if (!data) redirect('/login');
  return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-950" dir="rtl"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4 rounded-3xl bg-[#07111f] p-7 text-white"><div><p className="font-bold text-emerald-300">وصلة · بوابة المسوّق</p><h1 className="mt-2 text-3xl font-black">مرحباً {data.profile.name}</h1><p className="mt-2 text-sm text-slate-300">حسابك الواحد لبرامج المتاجر ونتائجها.</p></div><Link href="/marketers" className="rounded-xl bg-[#13c4a3] px-5 py-3 font-bold text-[#07111f]">انضم لبرنامج متجر</Link></header>
    <section className="grid gap-4 sm:grid-cols-3"><Card label="برامج متاجر معتمدة" value={String(data.affiliates.length)}/><Card label="طلبات قيد المراجعة" value={String(data.applications.filter(item => item.status === 'PENDING').length)}/><Card label="إجمالي الزيارات" value={data.affiliates.reduce((sum, item) => sum + item._count.visits, 0).toLocaleString('ar-SD')}/></section>
    <section><h2 className="mb-3 text-xl font-black">برامجك النشطة</h2><div className="grid gap-4 lg:grid-cols-2">{data.affiliates.map(item => { const link = `/store/${item.merchant.slug}/affiliate/${item.code}`; const pending = item.totals.filter(row => row.status === 'PENDING').reduce((sum, row) => sum + row.amount, 0); const paid = item.totals.filter(row => row.status === 'PAID').reduce((sum, row) => sum + row.amount, 0); return <article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between"><div><h3 className="font-black">{item.merchant.name}</h3><p className="mt-1 text-sm text-slate-500">{item._count.visits} زيارة · {item._count.attributions} طلب منسوب</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">نشط</span></div><code dir="ltr" className="mt-4 block break-all rounded-xl bg-slate-100 p-3 text-xs select-all">{link}</code><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 p-3"><p className="text-slate-500">معلّق</p><b>{pending.toLocaleString()} {item.program.currency}</b></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-slate-500">مدفوع</p><b>{paid.toLocaleString()} {item.program.currency}</b></div></div><p className="mt-3 text-xs text-slate-500">الهوية: {item.identityVerification?.status === 'APPROVED' ? 'مؤكدة' : 'مطلوبة'} · السداد: {item.payoutProfile ? 'مكتمل' : 'مطلوب'}</p></article>; })}{!data.affiliates.length&&<p className="rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500 lg:col-span-2">لم تُقبل في برنامج متجر بعد. قدّم طلباً من صفحة البرامج.</p>}</div></section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="font-black">طلبات الانضمام</h2><div className="mt-4 space-y-3">{data.applications.map(item => <div key={item.id} className="flex flex-wrap justify-between gap-3 rounded-xl bg-slate-50 p-4 text-sm"><span>{item.type === 'STOREFRONT_PRODUCTS' ? `تسويق منتجات · ${item.merchant?.name ?? 'متجر'}` : 'استقطاب تجار وصلة'}</span><b>{item.status === 'PENDING' ? 'قيد المراجعة' : item.status === 'APPROVED' ? 'مقبول' : 'مرفوض'}{item.rejectionReason ? ` · ${item.rejectionReason}` : ''}</b></div>)}{!data.applications.length&&<p className="text-sm text-slate-500">لا توجد طلبات بعد.</p>}</div></section>
  </div></main>;
}
function Card({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></article>; }
